name: CI

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

  release:
    types: [published]

jobs:

  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --with style
      - name: Check style with black
        run: poetry run black --check .
      - name: Check style with isort
        run: poetry run isort --check .
        
  type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --with type
      - name: Check type
        run: poetry run pyright
      - name: Check untyped function
        run: poetry run mypy ./crenata
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: rena
        ports:
          - 127.0.0.1:5432:5432
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --with test
      - name: Check test
        run: poetry run pytest --asyncio-mode=auto




        
